name: CI

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt update
        sudo apt install -y python3-can python3-serial python3-setuptools python3-pyelftools python3-qtpy python3-wheel libtinfo5
    - name: test
      run: ./travis-ci.sh
